import React from 'react';
import './../HowReactWorks/HowReactWorks.css'
const HowUseStateWorks = () => {
    return (
        <div className='qa-container'>
            <h2>How does useState() work?</h2>
            <p><b>Ans: </b> useState() is a React Hook which enables us to add state to different function components. <br></br>A single piece of state associated with that component is generated by calling React.useState inside a function component.
            </p>
            <p>Using the useState hook we can declare one or more state variables in function components. Inside, React keeps track of these state variables as well as ensuring that they always stay up-to-date on subsequent re-renders of the component</p>
        </div>
    );
};

export default HowUseStateWorks;